### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by igitur** [stackify/redis-tagging-locking-sample#2]
Hi all,

I realise this repo hasn't had any action in years, but maybe you can help me out. 

I was looking for a Redis/memcache/etc-based tagging cache and found your blog at https://stackify.com/implementing-cache-tagging-redis/ and it looks exactly like what we need. NCache also seems to have something like this, but only in the Enterprise edition.

So I checked out the code and immediately ran the test suite and had 3 failing tests. I found that at commit 24d633e4d0b3b28769de4c277d1c633caeb3821e the tests were still working. Did a `git bisect` and found that d97c632f4bb316468d55e6f455d1b02b6bf8acef is the first bad commit. (Btw, isn't `git bisect bad master` the best git command ever? ;-) )

Also the DistributedLockingPerMethod code doesn't seem to represent the binary that is also included in the repo. In summary, the latest commit doesn't really have anything that's working.

I'm trying to look into the reasons, but to be honest, there's a lot of new concepts for me (Postsharp, etc), so I'm not sure I'll figure it out, but I'll give it my best. 

I know this is open-source and I'm not owed anything, but if you have spare cycles, would you be able to see if there's an easy fix for this?

thanks

**Comment by t-lair** [comment]
@igitur This was a one off project that was made for the purpose of that blog post

**Comment by igitur** [comment]
Noted.
